contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://chenyuhang.xyz/"
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "陈的个人站"
  author = "Michael"
